### ISSUE TITLE
Unable to Re-Compile for Unreal Engine 4.20

### ISSUE THREAD

**Issue by DatapawWolf** [mik14a/VOX4U#11]
I know that Unreal Engine 4.20 was recently released but I was wondering if you had any plans to release an update to make this compatible with the newest update. It does not appear that the newest engine version is able to re-compile the plugins.

**Comment by ryangadz** [comment]
check out my branch its been confirmed to compile with 4.20 https://github.com/ryangadz/VOX4U

I have not checked 4.20.1 yet

**Comment by mik14a** [comment]
Very thanks @ryangadz .
I understood what going on this repo with UE 4.20.
I'll fix the legacy include for new unity build system.
And soon build plugin package for UE 4.20.
Thanks.

**Comment by mik14a** [comment]
Thanks @DatapawWolf  and @ryangadz .
Plugin source fixed for 4.20 and packaged new release.
