### ISSUE TITLE
UE 4.26 crash after .vox import

### ISSUE THREAD

**Issue by Maxyeah** [mik14a/VOX4U#15]
Hi, 
i try to import the MagicaVoxel template vox models to UE 4.26 with your plugin. 
But after pressing import, UE crashes. Bevor crashing the Content Browser shows some files. But after restart the files are gone.

I´m working with win10 x64 and MagicaVoxel 0.99.6.3

[UE4CC-Windows-E831ABB440515D1235891E8A4162A1EF_0000.zip](https://github.com/mik14a/VOX4U/files/5932471/UE4CC-Windows-E831ABB440515D1235891E8A4162A1EF_0000.zip)

**Comment by Maxyeah** [comment]
Importing the other typs work well

**Comment by Maxyeah** [comment]
I tried with MagicaVoxel 099.6.2 with same results 

LowLevelFatalError [File:C:\Program Files\Epic Games\UE_4.26\Engine\Source\Editor\UnrealEd\Classes\ThumbnailRendering/ThumbnailRenderer.h] [Line: 70] Pure virtual not implemented (UThumbnailRenderer::Draw)

**Comment by KittenCat99** [comment]
I get the same issue I have tried everything

**Comment by KittenCat99** [comment]
I use 4.25.4

**Comment by mik14a** [comment]
Thanks @Maxyeah  and @KittenCat99 .
It was a bug in importing in Voxel format.
Fixed in 705b7d505dfdfda7ce675d762495cc30cb2e6a55.
