### ISSUE TITLE
Update to 4.17 or 4.18

### ISSUE THREAD

**Issue by HeadClot** [mik14a/VOX4U#2]
Would it be possible to update this plugin to 4.17 or 4.18?

**Comment by Starkium** [comment]
I'd love it if this could be updated to 4.18. I'm not super strong with c++, but I'm more than willing to help if I can get some direction or assistance.

**Comment by mik14a** [comment]
Thanks @HeadClot ,@Starkium and  @Phyronnaz. And errors of unknown chunks are fixed soon.
