### ISSUE TITLE
Destructible Mesh

### ISSUE THREAD

**Issue by ruohki** [mik14a/VOX4U#8]
No Issue

How did you create that blocky destructible meshes?

**Comment by mik14a** [comment]
Hi @ruohki .
UnrealEditor able to build a DestructibleMesh from StaticMeshes using NVidia Apex functions without a [PhysXLab app](https://developer.nvidia.com/apex-destruction-physxlab-tutorials).
'SetupChunksFromStaticMeshes' function called by 'Import FBX Chunks' in destructible actors editor window.
That function need array of StaticMesh.
I'm using that function; simple way create cubed RowMesh from each voxel and build a array of StaticMesh.
https://github.com/mik14a/VOX4U/blob/master/Source/VOX4UEditor/Private/VoxelFactory.cpp#L245

**Comment by ruohki** [comment]
Oh great got it working but when fracturing (destroying) a voxel DM the whole game starts to freeze for a little amount of time.

**Comment by thejustinwalsh** [comment]
As the above was still unclear to me, I did this...
1. Import VOX as a Destructible mesh in UE4
2. Right click Imported Destructible Mesh and select `Asset Actions -> Export` and export to FBX
3. Open the Destructible Mesh in the Destructable Mesh Editor and click on `Import FBX Chunks` then select your exported FBX from step 2.
4. Profit
