### ISSUE TITLE
Static Lighting on Meshes are solid black

### ISSUE THREAD

**Issue by SirWesleyIV** [mik14a/VOX4U#9]
If Static Lighting is enabled and the object is set to 'Stationary' the object becomes completely black after lighting is built.

**Comment by laggyluk** [comment]
Any progress on that? Mesh needs second UV channel with different unwrapping than 'palette stripe' but when I test that process with blender, UE4 bake still results in many artifacts. Maybe static lighting just can't handle voxel mesh topology well?

**Comment by mik14a** [comment]
Hi @SirWesleyIV 
The texture assigned to the voxel's mesh is a 1 pixel x 1 pixel texture, and no UVs are generated for use in light maps.
This is an issue of strategy in meshing voxels, and it is undecided whether this will be addressed in the future.
Please use a dynamic light.
